version: "3.8"
services:
  kuzco-main:
    container_name: kuzco-main
    build: .
    networks:
      - kuzco-network
    restart: always
    environment:
      NODE_ENV: "production"
      CODE: "ec43aa23-53b4-4f9d-bc08-0382bba9e1bd"
      VIKEY_API_KEY: "vk-pphs415Sgij4cn4eAFZAczoS1FqtD1"
      GPU0_NAME: "NVIDIA GeForce RTX 4090"

networks:
  kuzco-network:
    driver: bridge
