name: Nexus Network Setup

on:
  workflow_dispatch:

jobs:
  setup-nexus-network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust (for building Nexus CLI)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Clone and Build Nexus CLI
        run: |
          git clone https://github.com/nexus-xyz/nexus-cli.git
          cd nexus-cli/clients/cli
          cargo build --release
          echo "$GITHUB_WORKSPACE/nexus-cli/clients/cli/target/release" >> $GITHUB_PATH

      - name: Start Nexus Network
        run: |
          nexus-network start --node-id 7054362
