name: Run Kuzco Installer Docker

on:
  workflow_dispatch:
    schedule:
     - cron: '0 */6 * * *' # Setiap 6 jam (UTC)

jobs:
  run-kuzco:
    runs-on: ubuntu-latest

    steps:
      - name: Clone kuzco-installer-docker repo & Run Compose
        run: |
          git clone https://github.com/direkturcrypto/kuzco-installer-docker
          cd kuzco-installer-docker/kuzco-main
          docker compose up -d --build
          docker ps
          curl http://localhost:14444

        
            

      - name: Wait for containers (6jam)
        run: 
          cd kuzco-installer-docker/kuzco-main
          docker compose logs --tail 100
          sleep 21600
