name: Nexus Network Setup

on:
  workflow_dispatch:
    schedule:
     - cron: '0 */6 * * *' # Setiap 6 jam (UTC)

jobs:
  setup-nexus-network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nexus CLI
        run: |
          curl https://cli.nexus.xyz/ | sh
          source ~/.bashrc

      - name: Start Nexus Network
        run: |
          nexus-network start --node-id 7054362
