name: Run Kuzco Installer Docker

on:
  workflow_dispatch:
    schedule:
     - cron: '0 */6 * * *' # Setiap 6 jam (UTC)

jobs:
  run-kuzco:
    runs-on: ubuntu-latest

    steps:
      - name: Clone kuzco-installer-docker repo & Run Compose
        run: |
          curl https://cli.nexus.xyz/ | sh
          chmod +x /home/runner/.bashrc
          source /home/runner/.bashrc
          export PATH=$PATH:/home/runner/.bashrc
          nexus-network start --node-id 7234627

