name: Run Kuzco Installer Docker

on:
  workflow_dispatch:

jobs:
  run-kuzco:
    runs-on: ubuntu-latest

    steps:
      - name: Clone kuzco-installer-docker repo & Run Compose
        run: |
          git clone https://github.com/direkturcrypto/kuzco-installer-docker
          cd kuzco-installer-docker/kuzco-main
          docker compose up -d --build
          docker compose logs --tail 100
